### ISSUE TITLE
Some differences between the autogenerated tarballs and release tarballs

### ISSUE THREAD

**Issue by musicinmybrain** [Qalculate/qalculate-qt#121]
There are some apparently-minor but surprising differences between the release tarballs, e.g.

https://github.com/Qalculate/qalculate-qt/releases/download/v5.0.0/qalculate-qt-5.0.0.tar.gz

and the automatically generated tarballs for the corresponding tags, e.g.

https://github.com/Qalculate/qalculate-qt/archive/v5.0.0/qalculate-qt-5.0.0.tar.gz

For 5.0.0, in the release archive:

- The `COPYING` file still has the old FSF postal address, from before 7dcaa6398cbf45a7f3c80e13bf6ee493170afbd9.
- The files `data/io.github.Qalculate.qalculate-qt.png` and `README.md` are absent.
- Several of the translation files `translations/qalculate-qt_??.qm` have different contents.

There are also a couple of unsurprising differences, e.g., `.gitignore` and `snap/` are not in the release archive.

I’m especially curious how the release archives are ending up with an old version of `COPYING`.

**Comment by hanna-kn** [comment]
The release archives are created manually, with the previous release as starting point. At some point I failed to notice or remember that `COPYING` had been updated, and this mistake has affected the tarballs since then.

The `qm` files (compiled translations) are not present in Git repository, and thus neither in the automatically generated tarballs.

`data/io.github.Qalculate.qalculate-qt.png` is only used in the `data/io.github.Qalculate.qalculate-qt.metainfo.xml` which points to the files location in Git (https://raw.githubusercontent.com/Qalculate/qalculate-qt/master/data/io.github.Qalculate.qalculate-qt.png).

To include both `README.md`, which is primarily intended for display on the Github project page, and `README` seems unncessary.
