### ISSUE TITLE
Not all Strings are NOT Translated

### ISSUE THREAD

**Issue by foreachthing** [Qalculate/qalculate-qt#8]
Q!-New (alos Q!) thinks that my OS is in German (I am located in Switzerland but my OS is set to English) and therefore I have to tell Q! to _Ignor system language_.
This works so far until you open the _Functions_:

![image](https://user-images.githubusercontent.com/10420187/129509670-00c00cd1-841d-4181-bd37-ced78da4903d.png)

Everything is in English until you scroll to the _Arguments_.

Then here:
![image](https://user-images.githubusercontent.com/10420187/129509973-ea21680b-57a6-4b70-a45d-6a1622f4cc9c.png)

And this:
![image](https://user-images.githubusercontent.com/10420187/129510390-359826ce-5c1c-406e-bcec-e9871c965266.png)

This is fo Q!-New only. Works in Q! as expected.

**Comment by hanna-kn** [comment]
The gettext version in MYS2/MinGW seems to use the regional format instead of the language setting in Windows. libqalculate uses LCIDToLocaleName(LOCALE_USER_DEFAULT, ...) for definitions with similar result. Qt seems to use the correct language. This results in correct language displayed on UI elements, but wrong language in messages (from libqalculate), and functions, variables, and units.

This does however not explain your issue, which I'm not able to reproduce (in my tests ignore system langauge changes the language of everything).

**Comment by foreachthing** [comment]
Woops!
My mistake: in Q!-new (does not use the same settings as Q!) I didn't have _Ignore system language_ enabled!
So it's a mix between English and German without this option set. After setting this setting to true it works as expected.
