### ISSUE TITLE
Automatically copy result to clipboard? | Expected behaviour in older GTK

### ISSUE THREAD

**Issue by davidjhi** [Qalculate/qalculate-qt#83]
Hello.

In older versions of Qalculate (GTK), the workflow was faster / ideal for our situation.

### **Automatically Copy of result instaed of operation**
The result of an operation its automatically passed to the clipboard. So you save those extras ms of pressing Ctrl+C.

Generally you we want to copy the result, and not operation, which can be copied from the history anyways.

Having to press Ctrl + Alt + C adds an step and modifies the standard workflow / keybinds of the main OS.

**Suggestion**
- Automatically copy the result after pressing "Enter" with the current operation (Maybe as an option in preferences?)
- Option in preferences to either copy the operation or result according to user needs.

** Press to copy result **
One workaround, that was present in older GTK; was just pressing the result in the history to instantly copy the result. Was very useful too.

**Comment by hanna-kn** [comment]
Current options for copying result:
Ctrl+Alt+C
Copy option in context menu of history
Select text in history and copy
Custom key binding
Custom keypad button

There are also an option in preferences to replace the expression with the result in the expression entry after calculation, but for some reason this does  not set the selection clipboard contents (I will fix this), for middle-click paste.

It would be easy to add an option to always copy the result after calculation, but this would be disabled by default (since I would personally find it annoying if the clipboard contents where repeatedly replaced).

**Comment by hanna-kn** [comment]
Done (option to automatically copy result has been added, in preferences dialog).
