### ISSUE TITLE
Additional Copy Options

### ISSUE THREAD

**Issue by sharkweek** [Qalculate/qalculate-qt#84]
I use units quite often and find myself frequently copying results to other programs like text editors and Excel. It would be very useful to have a little more control over how results are copied. For example, being able to copy the results as unformatted ASCII _without_ the appended units would be very useful. Or being able to copy using a different precision or notation format from the as-displayed result could also be helpful.

I'm not sure what the best way to implement these types of options would be, but my first thought is to provide independent settings for copy from those of the displayed result. I would also propose an option to select the default copy method (i.e. as-displayed or ASCII).

**Comment by hanna-kn** [comment]
I've now added an option to remove units from copied unformatted ASCII. There is already an option to copy unformatted ASCII by default (in preferences).

I find it difficult to imagine a simple way to implement separate formatting options for copying (especially since these may change depending on context). I would primarily suggest assigning keyboard shortcuts to desired formatting options (I've now added set precision and toggle max/min decimals to available actions).

**Comment by sharkweek** [comment]
Thanks @hanna-kn!

Also, I just realized that my comment about changing the default copy was based on the gtk UI. The multiple precision options for copy vs. display, though, would be for both UIs.

**Comment by hanna-kn** [comment]
The same options have now been added to the GTK UI. I've also added the option to add multiple actions to a keyboard shortcut (this will also be added to the QT UI), which makes it possible to assign a single keyboard shortcut to change settings, copy the result and then restore the settings.

**Comment by sharkweek** [comment]
Awesome! I look forward to the next release!
